# Generated by Django 5.2.3 on 2025-06-30 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_address_customuser_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='staff_type',
            field=models.CharField(blank=True, choices=[('counsellor', 'Counsellor'), ('admin', 'Admin Staff'), ('housekeeping', 'Housekeeping'), ('online_ordering', 'Online Ordering'), ('staff', 'General Staff')], help_text='Type of staff (if role is staff)', max_length=30, null=True),
        ),
    ]
